spring.application.name=patient-service
server.port=4000
# Database Configuration - DEV H2 - OUTSIDE DOCKER
#spring.datasource.url=jdbc:h2:mem:patientdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=update
#spring.sql.init.mode=always
#spring.h2.console.path=/h2-console

# kafka
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer

# logging
logging.level.root=INFO
# Show your project's logs at INFO level
logging.level.com.patientmanagement=INFO
# Show the pattern nicely
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n

# postgres
